# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import base_msgs_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='dev_msgs.proto',
  package='AssisiMsg',
  serialized_pb='\n\x0e\x64\x65v_msgs.proto\x12\tAssisiMsg\x1a\x0f\x62\x61se_msgs.proto\"\xe8\x01\n\nRangeArray\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.AssisiMsg.Header\x12\x32\n\x04type\x18\x02 \x01(\x0e\x32 .AssisiMsg.RangeArray.SensorType:\x02IR\x12\x1d\n\rfield_of_view\x18\x03 \x01(\x02:\x06\x30.5236\x12\x14\n\tmin_range\x18\x04 \x01(\x02:\x01\x30\x12\x16\n\tmax_range\x18\x05 \x01(\x02:\x03inf\x12\r\n\x05range\x18\x06 \x03(\x02\x12\x11\n\traw_value\x18\x07 \x03(\x02\"\x14\n\nSensorType\x12\x06\n\x02IR\x10\x00\">\n\x0bTemperature\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.AssisiMsg.Header\x12\x0c\n\x04temp\x18\x02 \x02(\x02\"C\n\x10TemperatureArray\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.AssisiMsg.Header\x12\x0c\n\x04temp\x18\x02 \x03(\x02\"O\n\tVibration\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.AssisiMsg.Header\x12\x0c\n\x04\x66req\x18\x02 \x02(\x02\x12\x11\n\tamplitude\x18\x03 \x02(\x02\"T\n\x0eVibrationArray\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.AssisiMsg.Header\x12\x0c\n\x04\x66req\x18\x02 \x03(\x02\x12\x11\n\tamplitude\x18\x03 \x03(\x02\"S\n\tDiffDrive\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.AssisiMsg.Header\x12\x10\n\x08vel_left\x18\x02 \x02(\x01\x12\x11\n\tvel_right\x18\x03 \x02(\x01\"\x9b\x01\n\x0e\x45MDeviceConfig\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.AssisiMsg.Header\x12\x32\n\x04mode\x18\x02 \x02(\x0e\x32$.AssisiMsg.EMDeviceConfig.DeviceMode\"2\n\nDeviceMode\x12\x0c\n\x08\x45LECTRIC\x10\x00\x12\x0c\n\x08MAGNETIC\x10\x01\x12\x08\n\x04HEAT\x10\x02\"S\n\rElectricField\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.AssisiMsg.Header\x12\x0c\n\x04\x66req\x18\x02 \x02(\x02\x12\x11\n\tintensity\x18\x03 \x02(\x02\"S\n\rMagneticField\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.AssisiMsg.Header\x12\x0c\n\x04\x66req\x18\x02 \x02(\x02\x12\x11\n\tintensity\x18\x03 \x02(\x02')



_RANGEARRAY_SENSORTYPE = descriptor.EnumDescriptor(
  name='SensorType',
  full_name='AssisiMsg.RangeArray.SensorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='IR', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=259,
  serialized_end=279,
)

_EMDEVICECONFIG_DEVICEMODE = descriptor.EnumDescriptor(
  name='DeviceMode',
  full_name='AssisiMsg.EMDeviceConfig.DeviceMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='ELECTRIC', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MAGNETIC', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HEAT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=772,
  serialized_end=822,
)


_RANGEARRAY = descriptor.Descriptor(
  name='RangeArray',
  full_name='AssisiMsg.RangeArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='header', full_name='AssisiMsg.RangeArray.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='AssisiMsg.RangeArray.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='field_of_view', full_name='AssisiMsg.RangeArray.field_of_view', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.5236,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='min_range', full_name='AssisiMsg.RangeArray.min_range', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_range', full_name='AssisiMsg.RangeArray.max_range', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=1e10000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='range', full_name='AssisiMsg.RangeArray.range', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='raw_value', full_name='AssisiMsg.RangeArray.raw_value', index=6,
      number=7, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RANGEARRAY_SENSORTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=279,
)


_TEMPERATURE = descriptor.Descriptor(
  name='Temperature',
  full_name='AssisiMsg.Temperature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='header', full_name='AssisiMsg.Temperature.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='temp', full_name='AssisiMsg.Temperature.temp', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=281,
  serialized_end=343,
)


_TEMPERATUREARRAY = descriptor.Descriptor(
  name='TemperatureArray',
  full_name='AssisiMsg.TemperatureArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='header', full_name='AssisiMsg.TemperatureArray.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='temp', full_name='AssisiMsg.TemperatureArray.temp', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=345,
  serialized_end=412,
)


_VIBRATION = descriptor.Descriptor(
  name='Vibration',
  full_name='AssisiMsg.Vibration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='header', full_name='AssisiMsg.Vibration.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='freq', full_name='AssisiMsg.Vibration.freq', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='amplitude', full_name='AssisiMsg.Vibration.amplitude', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=414,
  serialized_end=493,
)


_VIBRATIONARRAY = descriptor.Descriptor(
  name='VibrationArray',
  full_name='AssisiMsg.VibrationArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='header', full_name='AssisiMsg.VibrationArray.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='freq', full_name='AssisiMsg.VibrationArray.freq', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='amplitude', full_name='AssisiMsg.VibrationArray.amplitude', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=495,
  serialized_end=579,
)


_DIFFDRIVE = descriptor.Descriptor(
  name='DiffDrive',
  full_name='AssisiMsg.DiffDrive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='header', full_name='AssisiMsg.DiffDrive.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vel_left', full_name='AssisiMsg.DiffDrive.vel_left', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vel_right', full_name='AssisiMsg.DiffDrive.vel_right', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=581,
  serialized_end=664,
)


_EMDEVICECONFIG = descriptor.Descriptor(
  name='EMDeviceConfig',
  full_name='AssisiMsg.EMDeviceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='header', full_name='AssisiMsg.EMDeviceConfig.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mode', full_name='AssisiMsg.EMDeviceConfig.mode', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EMDEVICECONFIG_DEVICEMODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=667,
  serialized_end=822,
)


_ELECTRICFIELD = descriptor.Descriptor(
  name='ElectricField',
  full_name='AssisiMsg.ElectricField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='header', full_name='AssisiMsg.ElectricField.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='freq', full_name='AssisiMsg.ElectricField.freq', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='intensity', full_name='AssisiMsg.ElectricField.intensity', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=824,
  serialized_end=907,
)


_MAGNETICFIELD = descriptor.Descriptor(
  name='MagneticField',
  full_name='AssisiMsg.MagneticField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='header', full_name='AssisiMsg.MagneticField.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='freq', full_name='AssisiMsg.MagneticField.freq', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='intensity', full_name='AssisiMsg.MagneticField.intensity', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=909,
  serialized_end=992,
)

_RANGEARRAY.fields_by_name['header'].message_type = base_msgs_pb2._HEADER
_RANGEARRAY.fields_by_name['type'].enum_type = _RANGEARRAY_SENSORTYPE
_RANGEARRAY_SENSORTYPE.containing_type = _RANGEARRAY;
_TEMPERATURE.fields_by_name['header'].message_type = base_msgs_pb2._HEADER
_TEMPERATUREARRAY.fields_by_name['header'].message_type = base_msgs_pb2._HEADER
_VIBRATION.fields_by_name['header'].message_type = base_msgs_pb2._HEADER
_VIBRATIONARRAY.fields_by_name['header'].message_type = base_msgs_pb2._HEADER
_DIFFDRIVE.fields_by_name['header'].message_type = base_msgs_pb2._HEADER
_EMDEVICECONFIG.fields_by_name['header'].message_type = base_msgs_pb2._HEADER
_EMDEVICECONFIG.fields_by_name['mode'].enum_type = _EMDEVICECONFIG_DEVICEMODE
_EMDEVICECONFIG_DEVICEMODE.containing_type = _EMDEVICECONFIG;
_ELECTRICFIELD.fields_by_name['header'].message_type = base_msgs_pb2._HEADER
_MAGNETICFIELD.fields_by_name['header'].message_type = base_msgs_pb2._HEADER
DESCRIPTOR.message_types_by_name['RangeArray'] = _RANGEARRAY
DESCRIPTOR.message_types_by_name['Temperature'] = _TEMPERATURE
DESCRIPTOR.message_types_by_name['TemperatureArray'] = _TEMPERATUREARRAY
DESCRIPTOR.message_types_by_name['Vibration'] = _VIBRATION
DESCRIPTOR.message_types_by_name['VibrationArray'] = _VIBRATIONARRAY
DESCRIPTOR.message_types_by_name['DiffDrive'] = _DIFFDRIVE
DESCRIPTOR.message_types_by_name['EMDeviceConfig'] = _EMDEVICECONFIG
DESCRIPTOR.message_types_by_name['ElectricField'] = _ELECTRICFIELD
DESCRIPTOR.message_types_by_name['MagneticField'] = _MAGNETICFIELD

class RangeArray(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RANGEARRAY
  
  # @@protoc_insertion_point(class_scope:AssisiMsg.RangeArray)

class Temperature(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEMPERATURE
  
  # @@protoc_insertion_point(class_scope:AssisiMsg.Temperature)

class TemperatureArray(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEMPERATUREARRAY
  
  # @@protoc_insertion_point(class_scope:AssisiMsg.TemperatureArray)

class Vibration(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VIBRATION
  
  # @@protoc_insertion_point(class_scope:AssisiMsg.Vibration)

class VibrationArray(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VIBRATIONARRAY
  
  # @@protoc_insertion_point(class_scope:AssisiMsg.VibrationArray)

class DiffDrive(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DIFFDRIVE
  
  # @@protoc_insertion_point(class_scope:AssisiMsg.DiffDrive)

class EMDeviceConfig(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMDEVICECONFIG
  
  # @@protoc_insertion_point(class_scope:AssisiMsg.EMDeviceConfig)

class ElectricField(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ELECTRICFIELD
  
  # @@protoc_insertion_point(class_scope:AssisiMsg.ElectricField)

class MagneticField(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MAGNETICFIELD
  
  # @@protoc_insertion_point(class_scope:AssisiMsg.MagneticField)

# @@protoc_insertion_point(module_scope)
